"""Add total_savings to settings

Revision ID: 6e677bf079cd
Revises: bcb45b3f60bf
Create Date: 2025-07-04 19:48:26.720167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e677bf079cd'
down_revision = 'bcb45b3f60bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_savings', sa.Numeric(10, 2), nullable=False, server_default="0.00"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('total_savings')

    # ### end Alembic commands ###
